force-app/main/default/objects/Chiffrage__c/Chiffrage__c.object-meta.xml
<CustomObject>
    <label>Chiffrage</label>
    <nameField>
        <label>Nom Chiffrage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chiffrages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chiffrage__c/fields/CodeTVA__c.field-meta.xml
<CustomField>
    <fullName>CodeTVA__c</fullName>
    <label>Code TVA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Chiffrage__c/fields/MontantACL__c.field-meta.xml
<CustomField>
    <fullName>MontantACL__c</fullName>
    <label>Montant ACL</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Chiffrage__c/fields/PourcentageRemise__c.field-meta.xml
<CustomField>
    <fullName>PourcentageRemise__c</fullName>
    <description>[TXREM]</description>
    <label>Pourcentage de remise</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ImputationDommages__c/ImputationDommages__c.object-meta.xml
<CustomObject>
    <label>Imputation et dommages</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Nom de IMPUTATION et DOMMAGES</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imputations et dommages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImputationDommages__c/fields/ImputabiliteChoc__c.field-meta.xml
<CustomField>
    <fullName>ImputabiliteChoc__c</fullName>
    <label>Imputabilité du choc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imputable</fullName>
            </value>
            <value>
                <fullName>Non imputable</fullName>
            </value>
            <value>
                <fullName>Non déclaré</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImputationDommages__c/fields/JustificationImputabilite__c.field-meta.xml
<CustomField>
    <fullName>JustificationImputabilite__c</fullName>
    <label>Justification de l&#39;imputabilité</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ImputabiliteChoc__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corrosion</fullName>
            </value>
            <value>
                <fullName>Chocs</fullName>
            </value>
            <value>
                <fullName>Grêle</fullName>
            </value>
            <value>
                <fullName>Effraction</fullName>
            </value>
            <value>
                <fullName>Peinture abimée</fullName>
            </value>
            <value>
                <fullName>Présence de tags</fullName>
            </value>
            <value>
                <fullName>Séquelles réparation</fullName>
            </value>
            <value>
                <fullName>Cassure</fullName>
            </value>
            <value>
                <fullName>Déchirure</fullName>
            </value>
            <value>
                <fullName>Salissure</fullName>
            </value>
            <value>
                <fullName>Usure</fullName>
            </value>
            <value>
                <fullName>Fuite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImputationDommages__c/fields/NumeroChoc__c.field-meta.xml
<CustomField>
    <fullName>NumeroChoc__c</fullName>
    <label>Numéro du choc</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/LigneChiffrage__c.object-meta.xml
<CustomObject>
    <label>Ligne de Chiffrage</label>
    <nameField>
        <displayFormat>LC-{0000}</displayFormat>
        <label>Ligne de Chiffrage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de Chiffrage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LigneChiffrage__c/fields/Chiffrage__c.field-meta.xml
<CustomField>
    <fullName>Chiffrage__c</fullName>
    <label>Chiffrage</label>
    <referenceTo>Chiffrage__c</referenceTo>
    <relationshipLabel>Lignes de Chiffrage</relationshipLabel>
    <relationshipName>Lignes_de_Chiffrage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/CodeAction__c.field-meta.xml
<CustomField>
    <fullName>CodeAction__c</fullName>
    <label>Code action</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/CodeCote__c.field-meta.xml
<CustomField>
    <fullName>CodeCote__c</fullName>
    <label>Code côté</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/CodePiece__c.field-meta.xml
<CustomField>
    <fullName>CodePiece__c</fullName>
    <label>Code Pièce</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/ImputationDommages__c.field-meta.xml
<CustomField>
    <fullName>ImputationDommages__c</fullName>
    <label>Imputation et dommages</label>
    <referenceTo>ImputationDommages__c</referenceTo>
    <relationshipLabel>Lignes de Chiffrage</relationshipLabel>
    <relationshipName>Lignes_de_Chiffrage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/IndicateurApplicationRemisesGlobales__c.field-meta.xml
<CustomField>
    <fullName>IndicateurApplicationRemisesGlobales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indicateur application remises globales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/IndicateurPQE__c.field-meta.xml
<CustomField>
    <fullName>IndicateurPQE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indicateur PQE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/IndicateurPRE__c.field-meta.xml
<CustomField>
    <fullName>IndicateurPRE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indicateur PRE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/IndicateurVE__c.field-meta.xml
<CustomField>
    <fullName>IndicateurVE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indicateur VE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/Libelle__c.field-meta.xml
<CustomField>
    <fullName>Libelle__c</fullName>
    <label>Libellé</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/LibelleLigne__c.field-meta.xml
<CustomField>
    <fullName>LibelleLigne__c</fullName>
    <label>Libellé de ligne</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/Matiere__c.field-meta.xml
<CustomField>
    <fullName>Matiere__c</fullName>
    <label>Matière</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/NomFournisseur__c.field-meta.xml
<CustomField>
    <fullName>NomFournisseur__c</fullName>
    <label>Nom fournisseur</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/NumeroLigne__c.field-meta.xml
<CustomField>
    <fullName>NumeroLigne__c</fullName>
    <label>Numéro de ligne</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/OrigineLigne__c.field-meta.xml
<CustomField>
    <fullName>OrigineLigne__c</fullName>
    <label>Origine ligne</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/OrigineProvenance__c.field-meta.xml
<CustomField>
    <fullName>OrigineProvenance__c</fullName>
    <label>Origine provenance</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/PrixHT__c.field-meta.xml
<CustomField>
    <fullName>PrixHT__c</fullName>
    <label>Prix HT</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/QuantitePiece__c.field-meta.xml
<CustomField>
    <fullName>QuantitePiece__c</fullName>
    <label>Quantité pièce</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/ReferencePieceConstructeur__c.field-meta.xml
<CustomField>
    <fullName>ReferencePieceConstructeur__c</fullName>
    <label>Référence pièce constructeur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/ReferencePieceFournisseur__c.field-meta.xml
<CustomField>
    <fullName>ReferencePieceFournisseur__c</fullName>
    <label>Référence pièce fournisseur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/TempsT1__c.field-meta.xml
<CustomField>
    <fullName>TempsT1__c</fullName>
    <label>Temps T1</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/TempsT2__c.field-meta.xml
<CustomField>
    <fullName>TempsT2__c</fullName>
    <label>Temps T2</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/TempsT3__c.field-meta.xml
<CustomField>
    <fullName>TempsT3__c</fullName>
    <label>Temps T3</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LigneChiffrage__c/fields/TempsTP__c.field-meta.xml
<CustomField>
    <fullName>TempsTP__c</fullName>
    <label>Temps TP</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LigneChiffrageController.cls
/** 
* @author: Adolphe Sonko
* @date : Création 05/07/2019
* @date : Modification 30/07/2019
* @description : Server side Controller of ModificationLigneschiffrage component.
*/
public class LigneChiffrageController {
	@auraEnabled 
    public static List<LigneChiffrage__c> listLignesChiffrage( String chiffrageId){
        
    	List<LigneChiffrage__c> ligneChiffrages = new List<LigneChiffrage__c>();
        
        ligneChiffrages =  [SELECT Id, Name, CodeAction__c ,CodeCote__c, CodePiece__c,CodeTVA__c,IndicateurApplicationRemisesGlobales__c,IndicateurPQE__c,IndicateurPRE__c,IndicateurVE__c,Libelle__c,LibelleLigne__c,Matiere__c,NomFournisseur__c,NumeroLigne__c,
        					OrigineLigne__c,OrigineProvenance__c,PrixHT__c,QuantitePiece__c,ReferencePieceConstructeur__c,ReferencePieceFournisseur__c,TempsT1__c,TempsT2__c,TempsT3__c,TempsTP__c, Chiffrage__c, Chiffrage__r.Name, Chiffrage__r.MontantACL__c, Chiffrage__r.PourcentageRemise__c,
                            ImputationDommages__c,ImputationDommages__r.Name,ImputationDommages__r.NumeroChoc__c, ImputationDommages__r.ImputabiliteChoc__c
                     		FROM LigneChiffrage__c where Chiffrage__c =:chiffrageId ORDER BY ImputationDommages__r.ImputabiliteChoc__c ASC];
        return ligneChiffrages;
        
    }

  //  @AuraEnabled public Chiffrage__c chiffrage;
    @AuraEnabled public ImputationDommages__c imputDom;
    @AuraEnabled public List<LigneChiffrage__c> lignesChiffrage;
    
    
    
     //MAP les lignes de-chiffrages-avec les dommages
    @auraEnabled 
    public static List<LigneChiffrageController> MapLigneChiffrage(String chiffrageId){
        
        Map<ImputationDommages__c , List<LigneChiffrage__c>> MapLigneDom = new  Map<ImputationDommages__c , List<LigneChiffrage__c>>();   
        List<LigneChiffrage__c> lignes = new List<LigneChiffrage__c>();
        MAP<Id, ImputationDommages__c> MapDommage = new Map<Id,ImputationDommages__c>();
        Set<Id> dommageIds = new Set<Id>();
        
    //    Chiffrage__c chiff = [select id , name FROM Chiffrage__c where Id =:chiffrageId] ;
        

        //Lignes Associées
        lignes =  listLignesChiffrage(chiffrageId);
        system.debug('Lignes de Chiffrage : '+lignes);
        //Dommages Associés
        for (LigneChiffrage__c l:lignes){
            dommageIds.add(l.ImputationDommages__c);
        }

        //Map Inputation Dommage
         
        for ( ImputationDommages__c imp: [Select Id, Name, NumeroChoc__c, ImputabiliteChoc__c, JustificationImputabilite__c FROM ImputationDommages__c where Id in :dommageIds]){
            MapDommage.put(imp.id, imp);
        }
        
        for (LigneChiffrage__c li: lignes){
            ImputationDommages__c inputDom = MapDommage.get(li.ImputationDommages__c);
            if(MapLigneDom.containsKey(inputDom)){
                MapLigneDom.get(inputDom).add(li);
            }else{
              /*  List<LigneChiffrage__c> ListservicesMap = new List<LigneChiffrage__c>();
                ListservicesMap.add(li);
                MapLigneDom.put(inputDom, ListservicesMap);  */
                MapLigneDom.put(inputDom, new List<LigneChiffrage__c>{li});
            }
        }
         
        List<LigneChiffrageController> itemList = new List<LigneChiffrageController>();
        for(ImputationDommages__c dom: MapLigneDom.keySet()){
            LigneChiffrageController item = new LigneChiffrageController();
          //  Item.chiffrage = chiff;
            item.imputDom = dom;
            item.lignesChiffrage = MapLigneDom.get(dom);
            itemList.add(item);
        }
        
        system.debug('itemList : ' + itemList);
        return itemList;
        
    }
    
    
    //=============== Sauvegarde de données ======
    
      @auraEnabled
      public  static void  sauvegarderLignes(List<LigneChiffrage__c> updatedData, List<string> deletedlignes ){

		  //Delete Lignes   
		  List<LigneChiffrage__c> lignesToDelete = new List<LigneChiffrage__c>();
          Chiffrage__c  parentChiffrageToUpdate = new Chiffrage__c(); 
          
          lignesToDelete = [select id from LigneChiffrage__c where id in : deletedlignes]; 
          if (lignesToDelete != null && lignesToDelete.size()>0 ){
              delete lignesToDelete;
              system.debug('Heree are the deleted lignes : ' + lignesToDelete);
          }
          
          //Upsert Lignes
          if (updatedData != null && updatedData.size()>0 ){
              parentChiffrageToUpdate = updatedData[0].Chiffrage__r ;
             
              //Upsert Lignes
              upsert updatedData;
              //Update Chiffrage
              update parentChiffrageToUpdate;
           
              system.debug('Here are the updatedData : ' + updatedData);
              system.debug('Here are the updated parent Chiffrage : ' + parentChiffrageToUpdate);
          }

       
      } 
    
    
    //=============== Suppression de données ======
    @AuraEnabled 
    public static void massDeleteLignesChiffrage(List<String> delIDs){
       
     List<LigneChiffrage__c> lstOfDeleteLignes =  new List<LigneChiffrage__c>();
         for(String st: delIDs){
             LigneChiffrage__c lg = new LigneChiffrage__c();
             lg.Id = (Id)st ;
             lstOfDeleteLignes.add(lg); 
          }
          
        if(lstOfDeleteLignes != null && lstOfDeleteLignes.size() > 0){
            Delete lstOfDeleteLignes;
            system.debug('Here are the Deleted Lignes Chiffrage : ' + lstOfDeleteLignes);
        }
          
 
    }
    
    //=============== method for fetch picklist values dynamic ======

    @AuraEnabled
    public static List < String > getselectOptions(sObject objObject, string fld) {
  //  public static Map <String, List<String> > getselectOptions(sObject objObject, List<String> listFields) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
     //   system.debug('listFields --->' + listFields);
        List < String > allOpts = new list < String > ();
     //   Map <String, List<String> > mapValuesByField = new Map <String, List<String> >();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();  
        
    /*    for (String fld: listFields) {
            // Get the list of picklist values for this field.
            list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
            // Add these values to the selectoption list.
            for (Schema.PicklistEntry a: values) {
                if(mapValuesByField.get(fld) != null){
                    mapValuesByField.get(fld).add(a.getValue());
                }else{
                    mapValuesByField.put(fld, new List<String>{a.getValue()});
                }
            }
        }*/
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        } 
        system.debug('allOpts ---->' + allOpts);
        allOpts.sort();
        return allOpts;
    }
    
    /** 
    * @author: Samy TOUBAL
    * @date : Création 29/08/2019
    * @description : fetch Picklist values from sObject
    */
    @AuraEnabled
    public static List <String> getselectPicklistOptions(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        List <String> allOpts = new list <String> ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map <String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list <Schema.PicklistEntry> values = fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
        allOpts.add(a.getValue());
        }
        system.debug('allOpts ---->' + allOpts);
        allOpts.sort();
        return allOpts;
    }

}