force-app/main/default/objects/PointRemarquable__c/PointRemarquable__c.object-meta.xml
<CustomObject>
    <label>Point remarquable</label>
    <nameField>
        <label>Point remarquable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points remarquables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PointRemarquable__c/fields/Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dossier</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Points remarquables</relationshipLabel>
    <relationshipName>PointRemarquable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PointRemarquable__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nouveau</fullName>
                <default>true</default>
                <label>Nouveau</label>
            </value>
            <value>
                <fullName>Vu</fullName>
            </value>
            <value>
                <fullName>Non pertinent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StatutDossierTest.cls
@isTest
public class StatutDossierTest {

     @isTest
     private static void TestCaseInsert(){
		Case c = new Case(NumeroMissionBCA__c  = '00001797');
    	insert c;
		
        PointRemarquable__c pr =new PointRemarquable__c (Name =' test point remarquable',Statut__c ='Nouveau');
         insert pr;

         Task t = new Task (Subject ='Appeler / Rappeler', status='Open');
         insert t;
         
         List<Case> cc = [select NumeroMissionBCA__c from case where id = :pr.Dossier__c];
         System.assertEquals(c.NumeroMissionBCA__c,'00001797');
	}
    
}