force-app/main/default/objects/PointRemarquable__c/PointRemarquable__c.object-meta.xml
<CustomObject>
    <label>Point remarquable</label>
    <nameField>
        <label>Point remarquable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points remarquables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PointRemarquable__c/fields/Dossier__c.field-meta.xml
<CustomField>
    <fullName>Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dossier</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Points remarquables</relationshipLabel>
    <relationshipName>PointRemarquable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PointRemarquable__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nouveau</fullName>
                <default>true</default>
                <label>Nouveau</label>
            </value>
            <value>
                <fullName>Vu</fullName>
            </value>
            <value>
                <fullName>Non pertinent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StatutDossier.cls
/** 
* @author: Menad CHABI
* @date : Creation 26/07/2019
* @date : Modification 19/07/2019
* @description : Vérifier les points remarquables et les tache liés a un dossier.
*/
global class StatutDossier {
    

  @InvocableMethod(label='StatutDossier' description='Vérifier qu’aucun point remarquable n est rattaché au dossier.')
    global static List<Case> getCasePRT(List<CaseRequest> requests) {
    
    CaseRequest req = requests[0] ;
    List<PointRemarquable__c > PointRemarquables = new List<PointRemarquable__c >();    
    PointRemarquables = [SELECT Id,Dossier__c, Statut__c FROM PointRemarquable__c where  Dossier__c =: req.CaseId];
        
    List<Case > Cases = new List<Case >();
    List<Case > listCasesToUpdate = new List<Case >();   
    Cases = [SELECT Id,Status  FROM Case where Id =: req.CaseId];
        
    List<Task > Tasks = new List<Task >();
    Tasks = [SELECT Id, Subject, WhatId, Status   FROM Task where WhatId  =: req.CaseId];
     
    
        system.debug('Tasks :' + Tasks); 
        
        if((PointRemarquables==null || PointRemarquables.isEmpty())&&(Tasks==null || Tasks.isEmpty())){
            system.debug('PointRemarquables is null '); 
        	Cases[0].Status ='Expertise'; 
            system.debug('Cases'+Cases);
            
        }
        
       boolean isPROpen = false ;
       boolean isTaskOpen = false ;
        
         if(PointRemarquables != null && PointRemarquables.size() > 0){
               
              for (PointRemarquable__c PR : PointRemarquables) {
              		if(PR.Statut__c == 'Nouveau' ) { 
                          isPROpen = true ;	
 						
               		}   
              }
  		}     
        
        if(Tasks != null && Tasks.size() > 0){
            system.debug('Tasksss'+Tasks);
            
              for (Task T : Tasks) {
              		if(T.Status == 'Open') { 
                        isTaskOpen = true ;	
               		}         
              }
        }
        
        if(!isPROpen && !isTaskOpen){
            Cases[0].Status ='Expertise';
            listCasesToUpdate.add(Cases[0]) ;
        }
    
       if(listCasesToUpdate != null && listCasesToUpdate.size()>0){
                update listCasesToUpdate;
                system.debug('listCasesToUpdate' + listCasesToUpdate); 
        }     
    	
        return listCasesToUpdate;
    }
    
    
    global class CaseRequest {

    
        @InvocableVariable(required=true)
        global ID CaseId;


  }
    
}