force-app/main/default/objects/JourPassage__c/JourPassage__c.object-meta.xml
<CustomObject>
    <label>Jour de Passage</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Jour de Passage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jours de Passage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JourPassage__c/fields/AdresseAgence2__c.field-meta.xml
<CustomField>
    <fullName>AdresseAgence2__c</fullName>
    <label>Adresse Agence 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/AdresseAgence3__c.field-meta.xml
<CustomField>
    <fullName>AdresseAgence3__c</fullName>
    <label>Adresse Agence 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/AdresseAgence__c.field-meta.xml
<CustomField>
    <fullName>AdresseAgence__c</fullName>
    <label>Adresse Agence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/CodePE__c.field-meta.xml
<CustomField>
    <fullName>CodePE__c</fullName>
    <label>Code PE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/CodePostalAgence__c.field-meta.xml
<CustomField>
    <fullName>CodePostalAgence__c</fullName>
    <label>Code Postal Agence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/CodeUSC__c.field-meta.xml
<CustomField>
    <fullName>CodeUSC__c</fullName>
    <label>Code USC</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/Jeudi__c.field-meta.xml
<CustomField>
    <fullName>Jeudi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Jeudi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/Lundi__c.field-meta.xml
<CustomField>
    <fullName>Lundi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lundi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/Mardi__c.field-meta.xml
<CustomField>
    <fullName>Mardi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mardi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/Mercredi__c.field-meta.xml
<CustomField>
    <fullName>Mercredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mercredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Référence</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/USCPoleExpertise__c.field-meta.xml
<CustomField>
    <fullName>USCPoleExpertise__c</fullName>
    <label>USC/Pole Expertise</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/Vendredi__c.field-meta.xml
<CustomField>
    <fullName>Vendredi__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vendredi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/VilleAgence__c.field-meta.xml
<CustomField>
    <fullName>VilleAgence__c</fullName>
    <label>Ville Agence</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JourPassage__c/fields/VillePassage__c.field-meta.xml
<CustomField>
    <fullName>VillePassage__c</fullName>
    <label>Ville passage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetJourPassage.cls
/** 
* @author: Adolphe Sonko
* @date : Creation 12/08/2019
* @date : Modification 14/08/2019
* @description : Récuperer le jour de passage correspondant.
*/
global class GetJourPassage {
    
	@InvocableMethod(label='GetJourPassage' description='Returns the list of jour de Passage corresponding to the input Postal Code .')
    global static List<JourPassageResult> GetJourPassage(List<JourPassageRequest> requests) {
        
    JourPassageResult res = new JourPassageResult() ;
    List<JourPassageResult> listResults = new List<JourPassageResult>() ;
        
    JourPassageRequest req = requests[0] ;
  //  decimal tempPostalCode = decimal.valueOf(req.postalCode.deleteWhitespace()) ; 
    List<JourPassage__c> jrsPassage = [SELECT AdresseAgence2__c,AdresseAgence3__c,AdresseAgence__c,CodePE__c,CodePostalAgence__c,CodeUSC__c,Jeudi__c,Lundi__c,Mardi__c,Mercredi__c,Reference__c,USCPoleExpertise__c,Vendredi__c,VilleAgence__c,VillePassage__c FROM JourPassage__c WHERE Reference__c =: req.postalCode ];
    
    if(jrsPassage != null && jrsPassage.size() > 0){
        
        res.jrPassage = jrsPassage[0] ;

    }else {
        JourPassage__c jrPass = new JourPassage__c() ;
        jrPass.Reference__c = req.postalCode ;
        jrPass.VillePassage__c = null ;
        jrPass.Lundi__c = true ;
        jrPass.Mardi__c = true ;
        jrPass.Mercredi__c = true ;
        jrPass.Jeudi__c = true ;
        jrPass.Vendredi__c = true ;
                
        res.jrPassage = jrPass ;
    } 
    
    String jours = '' ;
    if(res.jrPassage.Lundi__c ){
        if(String.isEmpty(jours)){
            jours = 'Lundi' ;
        }else{
            jours = jours + ',  ' + 'Lundi' ;
        }
    }
    if(res.jrPassage.Mardi__c){
        if(String.isEmpty(jours)){
            jours = 'Mardi' ;
        }else{
            jours = jours + ',  ' + 'Mardi' ;
        }
    }
    if(res.jrPassage.Mercredi__c){
        if(String.isEmpty(jours)){
            jours = 'Mercredi' ;
        }else{
            jours = jours + ',  ' + 'Mercredi' ;
        }
    }
    if(res.jrPassage.Jeudi__c){
        if(String.isEmpty(jours)){
            jours = 'Jeudi' ;
        }else{
            jours = jours + ',  ' + 'Jeudi' ;
        }
    }
    if(res.jrPassage.Vendredi__c){
        if(String.isEmpty(jours)){
            jours = 'Vendredi' ;
        }else{
            jours = jours + ',  ' + 'Vendredi' ;
        }
    }
        
    res.jours = jours ;  
    listResults.add( res) ;
    return listResults;
       
  }
    
    
    class week{
        List<Jour> jours ;
    }
    class Jour{
        Boolean jour;
        String name;
    }
    
   global class JourPassageRequest {
        @InvocableVariable(required=true)
        global Decimal postalCode;
   }
    
   global class JourPassageResult {
        @InvocableVariable
        global JourPassage__c jrPassage;
       
        @InvocableVariable
        global String jours;
   }
}